export const searchInput = '//input[@id="gh-ac"]';
export const searchButton = '//button[@id="gh-search-btn"]';
export const sonyCheckbox = '//input[@aria-label="Sony"]';
export const priceFilter = '//div[text()="Price"]';
export const minPrice = '//input[@aria-label="Minimum Value in $"]';
export const maxPrice = '//input[@aria-label="Maximum Value in $"]';
export const thirdItem = '//li[@data-view="mi:1686|iid:3"]//div[@class="su-image"]';
export const selectOptionBtn = '//span[text()="Option:"]';
export const optionItem = '//div[@role="option" and not(@aria-selected="true")]';
export const addToCartBtn = '//span[text()="Add to cart"]';
export const searchResultsUrl = '**/sch/**';
export const searchResultsContainer = '.srp-results';
export const seeInCartBtn = '//a[contains(@class,"fake-btn--primary")]//span[text()="See in cart"]';
export const goToCheckoutBtn = '//button[text()="Go to checkout"]';
export const checkOutAsGuestBtn = '//button[@data-testid="modal-gxo-link"]';
export const shippingAddressForm = '//div[@data-test-id="SHIPPING_ADDRESS_FORM"]';
export const removeFromCartBtn = '//button[contains(@class,"number-input__delete")]';
export const emptyCartMessage = '//span[text()="You don\'t have any items in your cart."]';
export const emailInput = '//input[@id="email"]';
export const firstNameInput = '//input[@id="firstName"]';
export const lastNameInput = '//input[@id="lastName"]';
export const streetAddressInput = '//input[@id="addressLine1"]';
export const cityInput = '//input[@id="city"]';
export const stateInput = '//input[@id="stateOrProvince"]';
export const zipCodeInput = '//input[@id="postalCode"]';
export const phoneInput = '//input[@id="phoneNumber"]';